"""empty message

Revision ID: 094a5080cbb2
Revises: ec4ad1d2d789
Create Date: 2021-05-10 15:23:34.590972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094a5080cbb2'
down_revision = 'ec4ad1d2d789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_transactions', sa.Column('asset_address', sa.String(length=64), nullable=True))
    op.add_column('tbl_transactions', sa.Column('settlement_address', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_transactions', 'settlement_address')
    op.drop_column('tbl_transactions', 'asset_address')
    # ### end Alembic commands ###
