"""empty message

Revision ID: 60e5d6f30231
Revises: 8748aff35eb1
Create Date: 2021-05-10 11:08:24.811486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e5d6f30231'
down_revision = '8748aff35eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_endpoints', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_endpoints', 'description')
    # ### end Alembic commands ###
