"""empty message

Revision ID: 86ba23906f34
Revises: 2f9fe855ccac
Create Date: 2019-03-08 09:20:38.399000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ba23906f34'
down_revision = '2f9fe855ccac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_members', sa.Column('phone', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_tbl_members_phone'), 'tbl_members', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_members_phone'), table_name='tbl_members')
    op.drop_column('tbl_members', 'phone')
    # ### end Alembic commands ###
