"""empty message

Revision ID: 8748aff35eb1
Revises: 
Create Date: 2021-05-09 15:32:55.302337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8748aff35eb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_members_created_on'), 'tbl_members', ['created_on'], unique=False)
    op.create_index(op.f('ix_tbl_members_email'), 'tbl_members', ['email'], unique=False)
    op.create_index(op.f('ix_tbl_members_modified_on'), 'tbl_members', ['modified_on'], unique=False)
    op.create_index(op.f('ix_tbl_members_name'), 'tbl_members', ['name'], unique=True)
    op.create_index(op.f('ix_tbl_members_phone'), 'tbl_members', ['phone'], unique=False)
    op.create_table('tbl_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('tech_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_on', sa.DateTime(), nullable=True),
    sa.Column('message_id', sa.String(length=64), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_settlements_completed_on'), 'tbl_settlements', ['completed_on'], unique=False)
    op.create_index(op.f('ix_tbl_settlements_created_on'), 'tbl_settlements', ['created_on'], unique=False)
    op.create_table('tbl_transaction_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('endpoint', sa.String(length=64), nullable=True),
    sa.Column('token', sa.String(length=256), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['tbl_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_endpoints_created_on'), 'tbl_endpoints', ['created_on'], unique=False)
    op.create_index(op.f('ix_tbl_endpoints_modified_on'), 'tbl_endpoints', ['modified_on'], unique=False)
    op.create_table('tbl_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('asset_address', sa.String(length=64), nullable=True),
    sa.Column('settlement_address', sa.String(length=64), nullable=True),
    sa.Column('endpoint', sa.Integer(), nullable=True),
    sa.Column('service', sa.Integer(), nullable=True),
    sa.Column('service_data', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint'], ['tbl_endpoints.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['tbl_members.id'], ),
    sa.ForeignKeyConstraint(['service'], ['tbl_services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_address')
    )
    op.create_index(op.f('ix_tbl_assets_created_on'), 'tbl_assets', ['created_on'], unique=False)
    op.create_index(op.f('ix_tbl_assets_modified_on'), 'tbl_assets', ['modified_on'], unique=False)
    op.create_table('tbl_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.Integer(), nullable=True),
    sa.Column('transaction_price', sa.Integer(), nullable=True),
    sa.Column('recieved_amount', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.Integer(), nullable=True),
    sa.Column('service', sa.Integer(), nullable=True),
    sa.Column('service_data', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.String(length=64), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('settlement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset'], ['tbl_assets.id'], ),
    sa.ForeignKeyConstraint(['endpoint'], ['tbl_endpoints.id'], ),
    sa.ForeignKeyConstraint(['service'], ['tbl_services.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['tbl_settlements.id'], ),
    sa.ForeignKeyConstraint(['status'], ['tbl_transaction_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_transactions_created_on'), 'tbl_transactions', ['created_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_transactions_created_on'), table_name='tbl_transactions')
    op.drop_table('tbl_transactions')
    op.drop_index(op.f('ix_tbl_assets_modified_on'), table_name='tbl_assets')
    op.drop_index(op.f('ix_tbl_assets_created_on'), table_name='tbl_assets')
    op.drop_table('tbl_assets')
    op.drop_index(op.f('ix_tbl_endpoints_modified_on'), table_name='tbl_endpoints')
    op.drop_index(op.f('ix_tbl_endpoints_created_on'), table_name='tbl_endpoints')
    op.drop_table('tbl_endpoints')
    op.drop_table('tbl_transaction_statuses')
    op.drop_index(op.f('ix_tbl_settlements_created_on'), table_name='tbl_settlements')
    op.drop_index(op.f('ix_tbl_settlements_completed_on'), table_name='tbl_settlements')
    op.drop_table('tbl_settlements')
    op.drop_table('tbl_services')
    op.drop_index(op.f('ix_tbl_members_phone'), table_name='tbl_members')
    op.drop_index(op.f('ix_tbl_members_name'), table_name='tbl_members')
    op.drop_index(op.f('ix_tbl_members_modified_on'), table_name='tbl_members')
    op.drop_index(op.f('ix_tbl_members_email'), table_name='tbl_members')
    op.drop_index(op.f('ix_tbl_members_created_on'), table_name='tbl_members')
    op.drop_table('tbl_members')
    # ### end Alembic commands ###
