"""empty message

Revision ID: 87f3085567cb
Revises: dec476ca43a8
Create Date: 2019-11-20 13:10:24.537377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f3085567cb'
down_revision = 'dec476ca43a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_deposits', sa.Column('transaction_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_deposits', 'transaction_hash')
    # ### end Alembic commands ###
