"""empty message

Revision ID: 8efa866ac8d7
Revises: 
Create Date: 2021-04-02 12:21:24.394546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efa866ac8d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_members_created_on'), 'tbl_members', ['created_on'], unique=False)
    op.create_index(op.f('ix_tbl_members_email'), 'tbl_members', ['email'], unique=False)
    op.create_index(op.f('ix_tbl_members_modified_on'), 'tbl_members', ['modified_on'], unique=False)
    op.create_index(op.f('ix_tbl_members_name'), 'tbl_members', ['name'], unique=True)
    op.create_index(op.f('ix_tbl_members_phone'), 'tbl_members', ['phone'], unique=False)
    op.create_table('tbl_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('remaining_time', sa.Integer(), nullable=True),
    sa.Column('payment_address', sa.String(length=64), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['tbl_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_assets_created_on'), 'tbl_assets', ['created_on'], unique=False)
    op.create_index(op.f('ix_tbl_assets_modified_on'), 'tbl_assets', ['modified_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_assets_modified_on'), table_name='tbl_assets')
    op.drop_index(op.f('ix_tbl_assets_created_on'), table_name='tbl_assets')
    op.drop_table('tbl_assets')
    op.drop_index(op.f('ix_tbl_members_phone'), table_name='tbl_members')
    op.drop_index(op.f('ix_tbl_members_name'), table_name='tbl_members')
    op.drop_index(op.f('ix_tbl_members_modified_on'), table_name='tbl_members')
    op.drop_index(op.f('ix_tbl_members_email'), table_name='tbl_members')
    op.drop_index(op.f('ix_tbl_members_created_on'), table_name='tbl_members')
    op.drop_table('tbl_members')
    # ### end Alembic commands ###
