"""empty message

Revision ID: 963238fe6898
Revises: 
Create Date: 2019-11-22 12:02:13.003026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963238fe6898'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_asset_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_asset_types_name'), 'tbl_asset_types', ['name'], unique=True)
    op.create_table('tbl_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_members_created'), 'tbl_members', ['created'], unique=False)
    op.create_index(op.f('ix_tbl_members_email'), 'tbl_members', ['email'], unique=False)
    op.create_index(op.f('ix_tbl_members_modified'), 'tbl_members', ['modified'], unique=False)
    op.create_index(op.f('ix_tbl_members_name'), 'tbl_members', ['name'], unique=True)
    op.create_index(op.f('ix_tbl_members_phone'), 'tbl_members', ['phone'], unique=False)
    op.create_table('tbl_sensor_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_sensor_types_name'), 'tbl_sensor_types', ['name'], unique=True)
    op.create_table('tbl_tag_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_tag_types_name'), 'tbl_tag_types', ['name'], unique=True)
    op.create_table('tbl_transaction_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mqtt_msg', sa.String(length=64), nullable=True),
    sa.Column('error_desc', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_transaction_errors_timestamp'), 'tbl_transaction_errors', ['timestamp'], unique=False)
    op.create_table('tbl_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['tbl_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_accounts_created'), 'tbl_accounts', ['created'], unique=False)
    op.create_index(op.f('ix_tbl_accounts_modified'), 'tbl_accounts', ['modified'], unique=False)
    op.create_table('tbl_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('asset_type', sa.Integer(), nullable=True),
    sa.Column('account', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account'], ['tbl_accounts.id'], ),
    sa.ForeignKeyConstraint(['asset_type'], ['tbl_asset_types.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['tbl_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_assets_created'), 'tbl_assets', ['created'], unique=False)
    op.create_index(op.f('ix_tbl_assets_modified'), 'tbl_assets', ['modified'], unique=False)
    op.create_table('tbl_deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account'], ['tbl_accounts.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['tbl_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_deposits_timestamp'), 'tbl_deposits', ['timestamp'], unique=False)
    op.create_table('tbl_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UID', sa.String(length=64), nullable=True),
    sa.Column('KEY', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('tag_type', sa.Integer(), nullable=True),
    sa.Column('account', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account'], ['tbl_accounts.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['tbl_members.id'], ),
    sa.ForeignKeyConstraint(['tag_type'], ['tbl_tag_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_tags_UID'), 'tbl_tags', ['UID'], unique=True)
    op.create_index(op.f('ix_tbl_tags_created'), 'tbl_tags', ['created'], unique=False)
    op.create_index(op.f('ix_tbl_tags_modified'), 'tbl_tags', ['modified'], unique=False)
    op.create_table('tbl_withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account'], ['tbl_accounts.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['tbl_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_withdrawals_timestamp'), 'tbl_withdrawals', ['timestamp'], unique=False)
    op.create_table('tbl_sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UID', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('sensor_type', sa.Integer(), nullable=True),
    sa.Column('parent_asset', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['tbl_members.id'], ),
    sa.ForeignKeyConstraint(['parent_asset'], ['tbl_assets.id'], ),
    sa.ForeignKeyConstraint(['sensor_type'], ['tbl_sensor_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_sensors_UID'), 'tbl_sensors', ['UID'], unique=True)
    op.create_index(op.f('ix_tbl_sensors_created'), 'tbl_sensors', ['created'], unique=False)
    op.create_index(op.f('ix_tbl_sensors_modified'), 'tbl_sensors', ['modified'], unique=False)
    op.create_table('tbl_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('tag_account_id', sa.Integer(), nullable=True),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('asset_account_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('transaction_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_account_id'], ['tbl_accounts.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['tbl_assets.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['tbl_sensors.id'], ),
    sa.ForeignKeyConstraint(['tag_account_id'], ['tbl_accounts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tbl_tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_transactions_timestamp'), 'tbl_transactions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_transactions_timestamp'), table_name='tbl_transactions')
    op.drop_table('tbl_transactions')
    op.drop_index(op.f('ix_tbl_sensors_modified'), table_name='tbl_sensors')
    op.drop_index(op.f('ix_tbl_sensors_created'), table_name='tbl_sensors')
    op.drop_index(op.f('ix_tbl_sensors_UID'), table_name='tbl_sensors')
    op.drop_table('tbl_sensors')
    op.drop_index(op.f('ix_tbl_withdrawals_timestamp'), table_name='tbl_withdrawals')
    op.drop_table('tbl_withdrawals')
    op.drop_index(op.f('ix_tbl_tags_modified'), table_name='tbl_tags')
    op.drop_index(op.f('ix_tbl_tags_created'), table_name='tbl_tags')
    op.drop_index(op.f('ix_tbl_tags_UID'), table_name='tbl_tags')
    op.drop_table('tbl_tags')
    op.drop_index(op.f('ix_tbl_deposits_timestamp'), table_name='tbl_deposits')
    op.drop_table('tbl_deposits')
    op.drop_index(op.f('ix_tbl_assets_modified'), table_name='tbl_assets')
    op.drop_index(op.f('ix_tbl_assets_created'), table_name='tbl_assets')
    op.drop_table('tbl_assets')
    op.drop_index(op.f('ix_tbl_accounts_modified'), table_name='tbl_accounts')
    op.drop_index(op.f('ix_tbl_accounts_created'), table_name='tbl_accounts')
    op.drop_table('tbl_accounts')
    op.drop_index(op.f('ix_tbl_transaction_errors_timestamp'), table_name='tbl_transaction_errors')
    op.drop_table('tbl_transaction_errors')
    op.drop_index(op.f('ix_tbl_tag_types_name'), table_name='tbl_tag_types')
    op.drop_table('tbl_tag_types')
    op.drop_index(op.f('ix_tbl_sensor_types_name'), table_name='tbl_sensor_types')
    op.drop_table('tbl_sensor_types')
    op.drop_index(op.f('ix_tbl_members_phone'), table_name='tbl_members')
    op.drop_index(op.f('ix_tbl_members_name'), table_name='tbl_members')
    op.drop_index(op.f('ix_tbl_members_modified'), table_name='tbl_members')
    op.drop_index(op.f('ix_tbl_members_email'), table_name='tbl_members')
    op.drop_index(op.f('ix_tbl_members_created'), table_name='tbl_members')
    op.drop_table('tbl_members')
    op.drop_index(op.f('ix_tbl_asset_types_name'), table_name='tbl_asset_types')
    op.drop_table('tbl_asset_types')
    # ### end Alembic commands ###
