"""empty message

Revision ID: d0a128c0e56d
Revises: 
Create Date: 2019-11-25 12:06:11.605802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a128c0e56d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_asset_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_asset_types_name'), 'tbl_asset_types', ['name'], unique=True)
    op.create_table('tbl_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_members_created'), 'tbl_members', ['created'], unique=False)
    op.create_index(op.f('ix_tbl_members_email'), 'tbl_members', ['email'], unique=False)
    op.create_index(op.f('ix_tbl_members_modified'), 'tbl_members', ['modified'], unique=False)
    op.create_index(op.f('ix_tbl_members_name'), 'tbl_members', ['name'], unique=True)
    op.create_index(op.f('ix_tbl_members_phone'), 'tbl_members', ['phone'], unique=False)
    op.create_table('tbl_sensor_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_sensor_types_name'), 'tbl_sensor_types', ['name'], unique=True)
    op.create_table('tbl_tags',
    sa.Column('tag_UID', sa.String(length=64), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tag_UID')
    )
    op.create_index(op.f('ix_tbl_tags_created'), 'tbl_tags', ['created'], unique=False)
    op.create_table('tbl_transaction_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mqtt_msg', sa.String(length=64), nullable=True),
    sa.Column('error_desc', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_transaction_errors_timestamp'), 'tbl_transaction_errors', ['timestamp'], unique=False)
    op.create_table('tbl_transaction_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_transaction_types_name'), 'tbl_transaction_types', ['name'], unique=True)
    op.create_table('tbl_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('KEY', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('asset_type', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_type'], ['tbl_asset_types.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['tbl_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_assets_created'), 'tbl_assets', ['created'], unique=False)
    op.create_index(op.f('ix_tbl_assets_modified'), 'tbl_assets', ['modified'], unique=False)
    op.create_table('tbl_asset_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('tag_UID', sa.Integer(), nullable=True),
    sa.Column('asset_tag_balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['tbl_assets.id'], ),
    sa.ForeignKeyConstraint(['tag_UID'], ['tbl_tags.tag_UID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UID', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('sensor_type', sa.Integer(), nullable=True),
    sa.Column('parent_asset', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['tbl_members.id'], ),
    sa.ForeignKeyConstraint(['parent_asset'], ['tbl_assets.id'], ),
    sa.ForeignKeyConstraint(['sensor_type'], ['tbl_sensor_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_sensors_UID'), 'tbl_sensors', ['UID'], unique=True)
    op.create_index(op.f('ix_tbl_sensors_created'), 'tbl_sensors', ['created'], unique=False)
    op.create_index(op.f('ix_tbl_sensors_modified'), 'tbl_sensors', ['modified'], unique=False)
    op.create_table('tbl_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_UID', sa.Integer(), nullable=True),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('transaction_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['tbl_assets.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['tbl_sensors.id'], ),
    sa.ForeignKeyConstraint(['tag_UID'], ['tbl_tags.tag_UID'], ),
    sa.ForeignKeyConstraint(['transaction_type_id'], ['tbl_transaction_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_transactions_timestamp'), 'tbl_transactions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_transactions_timestamp'), table_name='tbl_transactions')
    op.drop_table('tbl_transactions')
    op.drop_index(op.f('ix_tbl_sensors_modified'), table_name='tbl_sensors')
    op.drop_index(op.f('ix_tbl_sensors_created'), table_name='tbl_sensors')
    op.drop_index(op.f('ix_tbl_sensors_UID'), table_name='tbl_sensors')
    op.drop_table('tbl_sensors')
    op.drop_table('tbl_asset_tags')
    op.drop_index(op.f('ix_tbl_assets_modified'), table_name='tbl_assets')
    op.drop_index(op.f('ix_tbl_assets_created'), table_name='tbl_assets')
    op.drop_table('tbl_assets')
    op.drop_index(op.f('ix_tbl_transaction_types_name'), table_name='tbl_transaction_types')
    op.drop_table('tbl_transaction_types')
    op.drop_index(op.f('ix_tbl_transaction_errors_timestamp'), table_name='tbl_transaction_errors')
    op.drop_table('tbl_transaction_errors')
    op.drop_index(op.f('ix_tbl_tags_created'), table_name='tbl_tags')
    op.drop_table('tbl_tags')
    op.drop_index(op.f('ix_tbl_sensor_types_name'), table_name='tbl_sensor_types')
    op.drop_table('tbl_sensor_types')
    op.drop_index(op.f('ix_tbl_members_phone'), table_name='tbl_members')
    op.drop_index(op.f('ix_tbl_members_name'), table_name='tbl_members')
    op.drop_index(op.f('ix_tbl_members_modified'), table_name='tbl_members')
    op.drop_index(op.f('ix_tbl_members_email'), table_name='tbl_members')
    op.drop_index(op.f('ix_tbl_members_created'), table_name='tbl_members')
    op.drop_table('tbl_members')
    op.drop_index(op.f('ix_tbl_asset_types_name'), table_name='tbl_asset_types')
    op.drop_table('tbl_asset_types')
    # ### end Alembic commands ###
