"""empty message

Revision ID: dec476ca43a8
Revises: 86ba23906f34
Create Date: 2019-03-12 15:41:14.693355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec476ca43a8'
down_revision = '86ba23906f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_assets', sa.Column('city', sa.String(length=64), nullable=True))
    op.add_column('tbl_assets', sa.Column('country', sa.String(length=64), nullable=True))
    op.add_column('tbl_assets', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('tbl_assets', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_assets', 'longitude')
    op.drop_column('tbl_assets', 'latitude')
    op.drop_column('tbl_assets', 'country')
    op.drop_column('tbl_assets', 'city')
    # ### end Alembic commands ###
