"""empty message

Revision ID: ec4ad1d2d789
Revises: 60e5d6f30231
Create Date: 2021-05-10 11:34:07.162938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4ad1d2d789'
down_revision = '60e5d6f30231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_endpoints', sa.Column('enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_endpoints', 'enabled')
    # ### end Alembic commands ###
